ALTER TABLE GO_APPUNTAMENTO
    ALTER COLUMN ID_MOTIVO BIGINT NULL;

ALTER TABLE GO_APPUNTAMENTO
    ADD TIPO_EVENTO VARCHAR(20) NULL;

UPDATE GO_APPUNTAMENTO
SET TIPO_EVENTO = 'APPUNTAMENTO'
WHERE 1 = 1;

ALTER TABLE GO_APPUNTAMENTO
    ALTER COLUMN TIPO_EVENTO VARCHAR(20) NOT NULL;

ALTER TABLE GO_APPUNTAMENTO
    ADD DESCRIZIONE VARCHAR(255) NULL;

CREATE TABLE GO_APPUNTAMENTO_VENDITORE
(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_APPUNTAMENTO BIGINT NOT NULL,
    COD_VENDITORE VARCHAR(3) NOT NULL
);

CREATE INDEX IX_GO_APPUNTAMENTO_VENDITORE_APP
    ON GO_APPUNTAMENTO_VENDITORE(ID_APPUNTAMENTO);


INSERT INTO GO_APPUNTAMENTO_VENDITORE
(
    ID_APPUNTAMENTO,
    COD_VENDITORE
)
SELECT
    ID,
    COD_VENDITORE
FROM GO_APPUNTAMENTO
WHERE COD_VENDITORE IS NOT NULL;

DROP INDEX IX_GO_APPUNTAMENTO_VENDITORE
    ON GO_APPUNTAMENTO;

ALTER TABLE GO_APPUNTAMENTO
    DROP COLUMN COD_VENDITORE;
ALTER TABLE GO_APPUNTAMENTO
    ALTER COLUMN NOME_CLIENTE VARCHAR(150) NULL;

CREATE TABLE GO_ASSENZA
(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,

    TIPO VARCHAR(20) NOT NULL,

    DATA_DA DATE NOT NULL,
    DATA_A DATE NOT NULL,

    ORA_DA TIME NULL,
    ORA_A TIME NULL,

    NOTE VARCHAR(1000) NULL,

    CREATED_AT DATETIME2 NULL,
    UPDATED_AT DATETIME2 NULL,

    CREATED_BY VARCHAR(100) NULL,
    UPDATED_BY VARCHAR(100) NULL
);

CREATE TABLE GO_ASSENZA_VENDITORE
(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,

    ID_ASSENZA BIGINT NOT NULL,

    COD_VENDITORE VARCHAR(3) NOT NULL
);

CREATE INDEX IX_GO_ASSENZA_VENDITORE_ASSENZA
    ON GO_ASSENZA_VENDITORE(ID_ASSENZA);

CREATE INDEX IX_GO_ASSENZA_DATA
    ON GO_ASSENZA(DATA_DA, DATA_A);