version: "3"
services:
  auth-service:
    environment:
      CORS_ORIGIN: "*"
      AUTH_DB_USER: "root"
      AUTH_DB_PASSWORD: "root"
      AUTH_URL: "jdbc:mysql://database-auth:3306/auth"
      CRYPTO_KEY: "PdSgVkYp3s6v9y/B"
      LOG_DIR: "/logs/auth-service.log"
      LOG_LEVEL: "ERROR"
    networks:
      - backend
      - frontend
    image: "pconvertini/ge-auth-api:1.3"
    container_name: "ge-auth-api"
    ports:
      - "8081:8081"
    depends_on:
      - database-auth
    volumes:
      - "/Users/pconvertini/IdeaProjects/gestione-ordini-be/jwt:/jwt"
      - "/Users/pconvertini/IdeaProjects/logs/gestione-ordini:/logs"
  api-service:
    environment:
      CORS_ORIGIN: "*"
      DB_USER: "sa"
      DB_PASSWORD: "D@tabas3"
      DB_URL: "jdbc:sqlserver://192.168.1.56:1433;database=master;encrypt=true;trustServerCertificate=true;"
      CRON_EXPR: "30m"
      ORDINI_PATH: "/Users/pconvertini/Documents/ordini/"
      FIRMA_ORDINI_PATH: "/Users/pconvertini/Documents/firme_ordini_clienti/"
      DATA_INIZIO: "2023-03-15"
      MAIL_FROM: "from@gmail.com"
      MAIL_HOST: "smtp.gmail.com"
      MAIL_PORT: "465"
      MAIL_USERNAME: "paolo.convertini@gmail.com"
      MAIL_PASSWORD: "uucffjibedgehgqk"
      LOG_DIR: "/logs/api-service.log"
      CRON_EXPR_NUOVI_ORDINI: "15m"
      LOG_LEVEL: "ERROR"
    networks:
      - backend
      - frontend
    image: "pconvertini/gestione-ordini-api:1.3"
    container_name: "ge-api"
    ports:
      - "8080:8080"
    volumes:
      - "/Users/pconvertini/IdeaProjects/gestione-ordini-be/jwt:/jwt"
      - "/Users/pconvertini/IdeaProjects/logs/gestione-ordini:/logs"
      - "/Users/pconvertini/Documents/ordini/:/ordini"
      - "/Users/pconvertini/Documents/firme_ordini_clienti/:/firme_ordini_clienti"
  database-auth:
    networks:
      - backend
    image: "mysql:8.0"
    container_name: "authenticate-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_DATABASE: "auth"
    volumes:
      - authdata:/var/lib/mysql
  client:
    environment:
      BACKEND_BASE_URL: "http://192.168.1.56:8080/api/"
      BACKEND_BASE_AUTH_URL: "http://192.168.1.56:8081/api/"
    networks:
      - frontend
    image: "pconvertini/gestione-ordini:1.8.1"
    container_name: "ge-frontend"
    ports:
      - "4200:80"
networks:
  frontend:
  backend:
volumes:
  authdata:

