version: "3"
services:
  auth:
    environment:
      CORS_ORIGIN: #INSERIRE IP
      AUTH_DB_USER: #user db
      AUTH_DB_PASSWORD: #user password
      CRYPTO_KEY: #secret key
      LOG_DIR: ###
    networks:
      - backend
      - frontend
    image: "pconvertini/ge-auth-api:1.0.0-SNAPSHOT"
    container_name: "ge-auth-api"
    ports:
      - "8081:8081"
    depends_on:
      - database-auth
    volumes:
      - /Users/pconvertini/IdeaProjects/gestione-ordini-be/jwt:/jwt
  api:
    environment:
      CORS_ORIGIN: #INSERIRE IP
      DB_USER: #user db
      DB_PASSWORD: #password db
      DB_URL: ###jdbc:sqlserver://localhost:1433;database=master;encrypt=true;trustServerCertificate=true;
      CRON_EXPR: ###30m
      ORDINI_PATH: ###
      FIRMA_ORDINI_PATH: ###
      DATA_INIZIO: ###
      MAIL_FROM: ###from@gmail.com
      MAIL_HOST: ###smtp.gmail.com
      MAIL_PORT: ###465
      MAIL_USERNAME: ###
      MAIL_PASSWORD: ###
      LOG_DIR: ###
    networks:
      - backend
      - frontend
    image: "pconvertini/gestione-ordini-api:1.0.0-SNAPSHOT"
    container_name: "ge-api"
    ports:
      - "8080:8080"
  database-auth:
    networks:
      - backend
    image: "mysql:8.0"
    container_name: "authenticate-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: auth
    volumes:
      - authdata:/var/lib/mysql
  client:
    environment:
      BACKEND_BASE_URL: ###
      BACKEND_BASE_AUTH_URL: ###
    networks:
      - frontend
    image: "pconvertini/gestione-ordini:1.4"
    container_name: "ge-frontend"
    ports:
      - "4200:80"
networks:
  frontend:
  backend:
volumes:
  apidata:
  authdata:

