CREATE TABLE GO_TRASPORTATORE (
    ID          varchar(36)          not null,
    NOME varchar(500) NOT NULL);

ALTER TABLE GO_TRASPORTATORE ADD CONSTRAINT GO_TRASPORTATORE_PK PRIMARY KEY ( ID );

create unique index GO_TRASPORTATORE_idx_1
    on GO_TRASPORTATORE (ID);


create index GO_TRASPORTATORE_idx_nome ON GO_TRASPORTATORE (NOME);