CREATE TABLE GO_QUADRATURA_CESPITE (
    ID          varchar(36)          not null,
    ID_CESPITE varchar(36) NOT NULL,
    ANNO int not null,
    AMMORTAMENTO float not null);

ALTER TABLE GO_QUADRATURA_CESPITE ADD CONSTRAINT GO_QUADRATURA_CESPITE_PK PRIMARY KEY ( ID );

create unique index GO_QUADRATURA_CESPITE_idx_1
    on GO_QUADRATURA_CESPITE (ID_CESPITE, ANNO);
