CREATE TABLE GO_FISCALE_RIEPILOGO
(
    ID                varchar(36)    not null,
    TIPO_CESPITE     varchar(3) not null,
    DESCRIZIONE      varchar(100)  NOT NULL,
    VALORE_AGGIORNATO float,
    AMMORTAMENTO_ORDINARIO float,
    AMMORTAMENTO_RIVALUTATO float,
    TOTALE_AMMORTAMENTO float,
    NON_AMMORTABILE float,
    FONDO_AMMORTAMENTI float,
    FONDO_AMMORTAMENTI_RIV float,
    SUPER_AMM1 float,
    SUPER_AMM2 float,
    SUPER_AMM3 float,
    SUPER_AMM4 float,
    PLUS float,
    MINUS float,
    RESIDUO float
);

ALTER TABLE GO_FISCALE_RIEPILOGO ADD CONSTRAINT GO_FISCALE_RIEPILOGO_PK PRIMARY KEY ( ID );

create unique index GO_FISCALE_RIEPILOGO_idx_1
    on GO_FISCALE_RIEPILOGO (TIPO_CESPITE);
