CREATE INDEX IDX_AMM_ID_ANNO
    ON GO_AMMORT_CESPITE (ID_AMMORTAMENTO, ANNO);

CREATE INDEX IDX_AMM_ANNO
    ON GO_AMMORT_CESPITE (ANNO);

CREATE INDEX IDX_CESPITE_ATTIVO
    ON GO_CESPITE (ATTIVO);

CREATE INDEX IDX_CESPITE_TIPO
    ON GO_CESPITE (TIPO_CESPITE);

CREATE INDEX IDX_CESPITE_ATTIVO_TIPO
    ON GO_CESPITE (ATTIVO, TIPO_CESPITE);