CREATE TABLE GO_FIRMAORDINECLIENTE
    (
        ANNO int NOT NULL,
        SERIE varchar(3) NOT NULL,
        PROGRESSIVO int NOT NULL,
        FILENAME varchar(100) NULL
);
ALTER TABLE GO_FIRMAORDINECLIENTE ADD CONSTRAINT FIRCLI00 PRIMARY KEY
    (
     ANNO ASC,
     SERIE ASC,
     PROGRESSIVO ASC
        )