SELECT
    CONSTRAINT_NAME,
    TABLE_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_NAME = 'USER'
  AND REFERENCED_COLUMN_NAME = 'id'
  AND TABLE_SCHEMA = DATABASE();

ALTER TABLE ROLE_PERMISSION
DROP FOREIGN KEY fk_role_perm_role;
ALTER TABLE USER_ROLE
DROP FOREIGN KEY FK52veh3j2tgvkrogjw2i0tucac;

ALTER TABLE ROLE
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE USER
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE USER_ROLE
    ADD CONSTRAINT FK52veh3j2tgvkrogjw2i0tucac
        FOREIGN KEY (role_id)
            REFERENCES ROLE(id);

ALTER TABLE ROLE_PERMISSION
    ADD CONSTRAINT fk_role_perm_role
        FOREIGN KEY (role_id)
            REFERENCES ROLE(id);