SELECT
    CONSTRAINT_NAME,
    TABLE_NAME
FROM information_schema.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_NAME = 'ROLE'
  AND REFERENCED_COLUMN_NAME = 'id'
  AND TABLE_SCHEMA = DATABASE();

ALTER TABLE <TABLE_NAME>
DROP FOREIGN KEY <CONSTRAINT_NAME>;

ALTER TABLE ROLE
    MODIFY id BIGINT NOT NULL AUTO_INCREMENT;

ALTER TABLE USER_ROLE
    ADD CONSTRAINT fk_user_role_role
        FOREIGN KEY (role_id)
            REFERENCES ROLE(id);

ALTER TABLE ROLE_PERMISSION
    ADD CONSTRAINT fk_role_perm_role
        FOREIGN KEY (role_id)
            REFERENCES ROLE(id);