INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'2381f85c-e8d7-475e-84bc-5c258aaabaaa', N'10A', N'Pannello fisso con barra stabilizzatrice, cristallo temprato 6 mm', N'Profilo Cromo - Cristallo Trasparente', N'88-90 cm', N'SX', 1, 627, N'90', N'10A_1', N'10A_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'2ad41376-44a6-476a-965e-b451ed79d203', N'10B', N'Pannello fisso con barra stabilizzatrice, cristallo temprato 6 mm', N'Profilo Cromo - Cristallo Trasparente', N'98-100 cm', N'SX', 1, 627, N'90', N'10B_1', N'10B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'9374db3b-a4b3-47fd-abfe-c254a5250b49', N'10C', N'Pannello fisso con barra stabilizzatrice, cristallo temprato 6 mm', N'Profilo Cromo - Cristallo Trasparente + Trattamento BrillBox', N'108-110 cm ', N'DX', 1, 696, N'90', N'10C_1', N'10C_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'82618cee-72aa-4ecb-a22c-5eed643ab5ed', N'10D', N'Pannello fisso con barra stabilizzatrice, cristallo temprato 6 mm', N'Profilo Nero - Cristallo Trasparente + Trattamento BrillBox', N'118-120 cm ', N'DX', 1, 875, N'15', N'10D_1', N'10D_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'4f159c56-d550-4f6c-9d27-52e87a84f1d8', N'12B', N'Porta scorrevole con sistema di scorrimento su cuscinetti a sfera, profilo di contenimento inferiore, cristallo temperato da 8+6 mm H. 200 cm. Due colli.', N'Profilo Cromo - Cristallo Trasparente.', N'108-110 cm', N'DX', 1, 1.161, N'50', N'12B_1', N'12B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'2aed76c2-3730-409a-ab88-22d178106f23', N'12B', N'Porta scorrevole con sistema di scorrimento su cuscinetti a sfera, profilo di contenimento inferiore, cristallo temperato da 8+6 mm H. 200 cm. Due colli.', N'Profilo Cromo - Cristallo Trasparente.', N'153,5-155,5 cm', N'SX', 1, 1.382, N'30', N'12B_1_SX', N'12B_2_SX', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'e2cf98b9-8191-4964-aa0a-1c55d52579f1', N'13B', N'Porta a battente con fisso in linea apertura esterna, chiusura magnetica, cristallo temperato da 6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente - Trattamento BrillBox', N'6,5-98,5 cm', N'DX', 1, 1.357, N'00', N'13B_1', N'13B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'e92277d3-a8fc-4766-a7c5-5add67e32256', N'14D', N'Box angolare scorrevole a due antine con sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'59-61 cm e 86-88 cm', N'SX', 1, 1.163, N'80', N'14D_1', N'14D_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'551f75ed-3862-4ede-9e35-5a6e9756ee83', N'14E', N'Box angolare scorrevole a due antine con sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'68-70 cm e 98-100 cm', N'SX', 1, 1.842, N'30', N'14E_1', N'14E_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'cee42963-524b-46e8-a92a-01c9aaeb07c7', N'17C', N'Box angolare con porta a battente, apertura esterna e fisso in linea, chiusura magnetica, cristallo temperato da 6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'76,5-78,5 cm e 97-99 cm', N'DX', 1, 1.572, N'00', N'17C_1', N'17C_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'99b262a2-c926-496a-bb9d-ae06f216fa5a', N'19B', N'Box angolare con porta scorrevole e laterale, sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'77-79 cm e 117-119 cm', N'SX', 1, 1.639, N'90', N'19B_1', N'19B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'0ed072e6-755d-4848-9069-43e7473ffd41', N'19C', N'Box angolare con porta scorrevole e laterale, sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'77-79 cm e 97-99 cm', N'DX', 1, 1.674, N'40', N'19C_1', N'19C_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'cef4410d-9dd2-4aaf-8589-007857d76d83', N'19D', N'Box angolare con porta scorrevole e laterale, sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'69-71 cm e 119 - 121 cm', N'DX', 1, 1.742, N'00', N'19D_1', N'19D_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'0bfbca77-7d82-4058-8f91-8334b16c2242', N'19D', N'Box angolare con porta scorrevole e laterale, sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'77-79 cm e 117-119 cm', N'DX', 2, 1.742, N'25', N'19D_1_DX', N'19D_2_DX', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'750c1dd2-98f6-40fd-bee8-9b41b85a39b1', N'19D', N'Box angolare con porta scorrevole e laterale, sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'67-69 cm e 117-119 cm', N'DX', 1, 1.742, N'00', N'19D_1_DX_67', N'19D_2_DX_67', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'a076fa95-32ce-49da-a7d9-ac59d5274a8c', N'19H', N'Box angolare con porta scorrevole e laterale, sistema di scorrimento su cuscinetti a sfera profilo di contenimento inferiore, chiusura magnetica, cristallo temperato da 8+6 mm H. 200 cm.', N'Profilo Argento Lucido - Cristallo Trasparente', N'68,5-70,5 cm e 118 - 120 cm', N'SX', 1, 1.742, N'00', N'19H_1', N'19H_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'c23c1f79-0e17-40ae-b3f2-8a6f2444e46b', N'261', N'Porta a soffietto antipanico, scorrevole su carrelli, chiusura magnetica, con possibilità di abbinamento a pannelli laterali, cristallo temprato da 3 mm.', N'Profilo Argento Lucido - Cristallo Stampato', N'74-80 cm', null, 1, 667, N'00', N'261_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'f699cf9c-a282-420b-bc4e-ac7cfb809783', N'273', N'Porta scorrevole su cuscinetti a sfera, anta sganciabile, chiusura magnetica, con possibilità di abbinamento a pannelli laterali, cristallo temperato da 3 mm.', N'Profilo Argento Satinato - Cristallo Trasparente ', N'122-128 cm', N'SX', 1, 725, N'65', N'273_1', N'273_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'c47c1dd8-1dca-49f5-a80a-bd03278598ea', N'290', N'Porta a due battenti (saloon), APERTURA TOTALE IN/OUT, chiusura magnetica, con possibilità di abbinamento a pannelli laterali, cristallo temperato da 3 mm.', N'Profilo Bianco - Cristallo Stampato ', N'68-74 cm', null, 1, 617, N'55', N'290_1', N'290_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'3a6a9f5f-6d29-44b9-a50e-2c69525b91d5', N'31B', N'Porta bilico, apertura esterna, chiusura magnetica, cristallo temperato da 6mm.', N'Profilo Cromo - Cristallo Trasparente', N'72-76 cm', N'SX', 1, 1.236, N'25', N'31B_1', N'31B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'46b6d8ce-a74a-4e57-ab8e-6d58c85a8a99', N'31C', N'Porta bilico, apertura esterna, chiusura magnetica, cristallo temperato da 6mm.', N'Profilo Cromo - Cristallo Trasparente - Trattamento BrillBox', N'80-84 cm', N'DX', 1, 1.298, N'35', N'31C_1', N'31C_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'950d5724-2b85-414d-93db-f764528b42da', N'324', N'Box a scomparsa a “L” con soffietti sollevabili con movimento a camme, ripiegabili a muro, chiusura ad incastro, lastre acrilico.', N'Profilo Bianco - Cristallo Gocce', N'78 cm ', null, 1, 808, N'45', N'324_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'8eb58c4e-270e-4e2a-bc77-ce0651bf6c51', N'351', N'Box angolare, reversibile, apertura scorrevole su cuscinetti a sfera, chiusura magnetica, possibilità di abbinamento a pannello jolly x formare “ U “, Lastre in acrilico.', N'Profilo Bianco . Cristallo Traslucido', N'68-80 cm', null, 1, 409, N'40', N'351_1', N'351_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'67121d72-520f-46c8-b1f1-ba7a764c4fcf', N'353', N'Box angolare, reversibile, apertura scorrevole su cuscinetti a sfera, chiusura magnetica, possibilità di abbinamento a pannello jolly x formare “ U “, Lastre in acrilico.', N'Profilo Bianco . Cristallo Traslucido', N'68-80 cm e 80-92 cm', null, 1, 420, N'90', N'353_1', N'353_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'a3936447-d4e1-4e69-b370-91d1dc860d59', N'44B', N'Doppia porta scorrevole serie BRIO 2015', N'Profilo Argento Lucido - Cristallo Velo', N'70-80 cm e 70-80 cm', null, 1, null, null, N'44B_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'00ee914f-0048-489c-a914-04ac6c244d89', N'44D', N'Doppia porta scorrevole serie BRIO 2015', N'Profilo Argento Lucido - Cristallo Velo', N'55-61 cm e 67-73 cm', null, 1, null, null, N'44D_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'bc7aa275-18a1-4267-b623-93be69537a09', N'54G', N'Box angolare apertura scorrevole su cuscinetti a sfera, ante sganciabili, chiusura magnetica, con possibilità di abbinamento a pannello laterale per formare una “U”', N'Profilo Cromo - Cristallo Satinato', N'67-70 cm e 97-100 cm', N'DX', 1, 1.239, N'70', N'54G_1', N'54G_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'3041531c-6408-4c47-aa58-49abae120684', N'81E', N'Box angolare apertura totale', N'Profilo Argento Lucido - Cristallo Trasparente - Trattamento BrillBox', N'75-77 cm e 81-83 cm', N'SX', 1, 1.163, N'00', N'81E_1', N'81E_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'457d17df-97ac-41bd-81de-a9c8cf4ee520', N'836', N'Box semicircolare, apertura scorrevole su cuscinetti a sfera, chiusura magnetica, lastre in cristallo temperato da 3 mm.', N'Profilo Argento Lucido - Cristallo Trasparente', N'88-90 cm', null, 1, 694, N'00', N'836_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'a5084b3c-f09a-4f3f-a29a-8cd0154d4d4f', N'89D', N'Porta due battenti apertura totale.', N'Profilo Cromo - Cristallo Trasparente', N'80-84 cm', null, 1, 841, N'00', N'89D_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'0fa35388-a100-4146-8a3f-b28d6ae93a08', N'8F9', N'Porta a due battenti apertura totale esterna/interna, chiusura magnetica, cristallo temperato da 6 mm.', N'Profilo Oro Specchio - Cristallo Satinato', N'88-92 cm', N'Reversibile', 1, 1.607, N'73', N'8F9_1', N'8F9_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'4f887eca-2cd2-4de0-8005-e737dc90af42', N'E0H', N'Articolo estensibile e componibile con tutti gli altri elementi costituenti la serie E per l’assemblaggio delle diverse tipologie.', N'Profilo Argento Lucido - Cristallo Trasparente', N'67-69 cm', null, 1, 381, N'80', N'E0H_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'91411bab-681a-4883-a010-63d7c8c69def', N'E0M', N'Articolo estensibile e componibile con tutti gli altri elementi costituenti la serie E per l’assemblaggio delle diverse tipologie.', N'Profilo Argento Lucido - Cristallo Trasparente', N'72-74 cm', null, 1, 409, N'40', N'E0M_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'71fa18dc-c5ad-4e73-ba48-67eae6cc3157', N'E0N', N'Articolo estensibile e componibile con tutti gli altri elementi costituenti la serie E per l’assemblaggio delle diverse tipologie.', N'Profilo Argento Lucido - Cristallo Trasparente', N'77-79 cm', null, 2, 425, N'50', N'E0N_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'ad7c99b9-710d-4118-ac29-6bb7552c013b', N'E2L', N'Porta a 2 ante scorrevole su cuscinetti a sfera, reversibile, chiusura magnetica, possibilità di abbinamento a pannello jolly per formare 2 o 3 lati, cristallo temperato 6 mm.', N'Profilo Argento Lucido - Cristallo Trasparente', N'136-142 cm', N'Reversibile', 2, 813, N'05', N'E2L_1', N'E2L_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'f4abdd86-4b02-484f-b2b2-fd72421b5972', N'E4K', N'Box angolare, componibile a lati, reversibile, apertura scorrevole su cuscinetti a sfera, chiusura magnetica, possibilità di abbinamento a pannello jolly per formare “U”, lastre in cristallo temperato da 6 mm.', N'Profilo Argento Lucido - Cristallo Trasparente', N'97-100 cm', null, 1, 569, N'25', N'E4K_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'6fcb6018-8398-4d8a-bd91-7e1ae7a13eea', N'E9B', N'Porta a due battenti (saloon), con APERTURA TOTALE IN/OUT, chiusura magnetica, possibilità di abbinamento a pannello jolly per formare “L” o “U”, lastre in cristallo temperato da 6 mm.', N'Profilo Argento Lucido - Cristallo Trasparente', N'74-80 cm', N'Reversibile', 1, 652, N'05', N'E9B_1', N'E9B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'acbf7a26-56c1-4a8b-a710-1589c0ec15fb', N'H5A', N'Porta a soffietto con APERTURA CENTRALE TOTALE IN/OUT, chiusura magnetica, cristallo temperato 6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente - Trattamento BrillBox', N'68-72 cm', N'SX', 1, 1.162, N'65', N'H5A_1', N'H5A_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'011ace8d-31d1-4c57-964f-f1158c802775', N'Q6B', N'Porta due battenti APERTURA TOTALE IN/OUT chiusura magnetica, cristallo temperato da 6 mm H. 200 cm.', N'Profilo Argento Lucido - Cristallo Satinato', N'71-75 cm', N'Reversibile', 1, 930, N'35', N'Q6B_1', N'Q6B_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'36e4c5da-f6ea-441f-b2cb-61270bbdb2cc', N'Q6D', N'Porta due battenti APERTURA TOTALE IN/OUT chiusura magnetica, cristallo temperato da 6 mm H. 200 cm.', N'Profilo Cromo - Cristallo Trasparente', N'87-91 cm', N'Reversibile', 1, 949, N'90', N'Q6D_1', N'Q6D_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'ddb95dd4-8aca-43d4-be23-466d988e2c59', N'S0A', N'Pannello fisso, cristallo temperato 6 mm, reversibile', N'Profilo Argento Lucido - Cristallo Trasparente', N'63-65 cm', N'Reversibile', 2, 400, N'20', N'S0A_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'11b678b7-bc43-4dde-92cf-0b7316f5f0b5', N'S0C', N'Pannello fisso, cristallo temperato 6 mm, reversibile', N'Profilo Argento Lucido - Cristallo Trasparente', N'77-79 cm', N'Reversibile', 2, 374, N'90', N'S0C_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'bb78cd1f-8aca-45be-b76f-5d522e7bc317', N'S2W', N'Porta a due ante scorrevoli al centro, con doppi cuscinetti a sfera e due pannelli fissi laterali, chiusura magnetica, con possibilità di abbinamento a pannelli laterali, cristallo temperato 6 mm.', N'Profilo Argento Lucido - Cristallo Trasparente', N'151-157 cm', N'Reversibile ', 1, 877, N'45', N'S2W_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'9b7767ad-0d28-424e-9ffd-3008dd0fb8c6', N'S3A', N'Porta a bilico reversibile con fisso in linea, apertura esterna, chiusura magnetica, possibilità di abbinamento a pannelli laterali, cristallo temperato da 6 mm', N'Profilo Argento Lucido - Cristallo Trasparente', N'97-103', null, 1, 676, N'20', N'S3A_1', N'', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'fc8e3b35-15bd-4889-ad85-a9d1ce5cd5e7', N'S4A+S4E', N'Angolare scorrevole con chiusura magnetica ad angolo. Carrelli con doppi cuscinetti a sfera, applicati direttamente sul cristallo. Possibilità di abbinamento a pannello fisso per formare una U.', N'Profilo Argento Lucido - Cristallo Trasparente', N'77-80 cm e 97-100 cm', N'SX', 1, 1.013, N'15', N'S4A+S4E_1', N'S4A+S4E_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'322b6fab-d9e5-4e86-b53e-9f0ff0bd9b63', N'S4D+S4E', N'Angolare scorrevole con chiusura magnetica ad angolo. Carrelli con doppi cuscinetti a sfera, applicati direttamente sul cristallo. Possibilità di abbinamento a pannello fisso per formare una U.', N'Profilo Argento Lucido - Cristallo Trasparente', N'S4D 77-80 cm e S4E 88-91 cm', N'Reversibile', 1, 1.018, N'90', N'S4D+S4E_1', N'S4D+S4E_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'f4038eeb-dae5-4bc2-8278-8ecd2ec8406f', N'S4P', N'Angolare scorrevole con chiusura magnetica ad angolo. Carrelli con doppi cuscinetti a sfera, applicati direttamente sul cristallo. Possibilità di abbinamento a pannello fisso per formare una U.', N'Profilo Argento Lucido - Cristallo Trasparente', N'77-80 cm e 97-100 cm', N'SX', 1, 1.132, N'75', N'S4P_1', N'S4P_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'650a2f82-e141-40a7-9af5-285cfc69d92d', N'S8E', N'Porta a soffietto antipanico, scorrevole su carrelli con doppio cuscinetto, chiusura magnetica, con possibilità di abbinamento a pannelli laterali, cristallo temprato 6 mm.', N'Profilo Argento Lucido - Cristallo Trasparente - Trattamento BrillBox', N'96-102 cm', N'Reversibile', 1, 1.047, N'65', N'S8E_1', N'S8E_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'2795a75f-ca58-4ca1-ab33-8692c68a0007', N'T2L', N'Box angolare con porta scorrevole e pannello laterale per montaggio ad angolo', N'Profilo Argento Lucido - Cristallo Trasparente', N'118,5-120 cm e 78-79,5 cm', N'SX', 1, 1.562, N'00', N'T2L_1', N'T2L_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'2aa92571-4027-4b81-bc61-9ec2426ca9da', N'T2T', N'Porta scorrevole con fisso in linea per montaggio in nicchia.', N'Profilo Cristallo Trasparente Serigrafato - Trattamento BrillBox', N'138,5-141,5 cm', N'DX', 3, null, null, N'T2T_1', N'T2T_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'41a73c1a-c5db-4125-956c-2dff5795d203', N'T7170EO', N'Cabina doccia ad angolo con apertura scorrevole.', N'Profilo Argento Lucido - Cristallo Satinato', N'117-122 cm', null, 1, null, null, N'T7170EO_1', N'T7170EO_2', DEFAULT);

INSERT INTO master.dbo.GO_BOX_DOCCIA (id, codice, descrizione, profilo, estensibilita, versione, qta, prezzo, extra, foto, posa, venduto) VALUES (N'813c7052-bcb5-4842-b84f-4b7173d859d9', N'T7336EO', N'Porta doccia con apertura scorrevole laterale.', N'Profilo Argento Lucido - Cristallo Satinato', N'107-112 cm', null, 1, null, null, N'T7336EO_1', N'T7336EO_2', DEFAULT);

