SELECT f.NUMEROBOLLA,f2.PROGRORDCLI, MAX(f.DATABOLLA) AS dataUltBolla
FROM FATTURE2 AS f2
         INNER JOIN FATTURE AS f ON f.ANNO = f2.ANNO AND f.SERIE = f2.SERIE AND f.PROGRESSIVO = f2.PROGRESSIVO
WHERE (f2.PROGRORDCLI <> 0)
GROUP BY f2.PROGRORDCLI,f.NUMEROBOLLA
order by dataUltBolla desc;