CREATE TABLE GO_SHOWROOM_MOTIVO (
                                    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
                                    DESCRIZIONE VARCHAR(150) NOT NULL,
                                    PARENT_ID BIGINT NULL,
                                    ATTIVO BIT NOT NULL DEFAULT 1,
                                    CONSTRAINT FK_GO_SHOWROOM_MOTIVO_PARENT
                                        FOREIGN KEY (PARENT_ID)
                                            REFERENCES GO_SHOWROOM_MOTIVO(ID)
);

CREATE TABLE GO_SHOWROOM_VISIT (
                                   ID BIGINT IDENTITY(1,1) PRIMARY KEY,
                                   NOME_CLIENTE VARCHAR(250) NOT NULL,
                                   COMUNE_ISTAT VARCHAR(10) NULL,
                                   TELEFONO VARCHAR(50) NULL,
                                   MOTIVO_ID BIGINT NOT NULL,
                                   VENDITORE_COD varchar(3) NULL,
                                   CODICE_CLIENTE VARCHAR(6) NULL,
                                   DATA_VISITA DATETIME2 NOT NULL DEFAULT GETDATE(),
                                   CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
                                   UPDATED_AT DATETIME2 NULL,
                                   CONSTRAINT FK_GO_SHOWROOM_MOTIVO
                                       FOREIGN KEY (MOTIVO_ID)
                                           REFERENCES GO_SHOWROOM_MOTIVO(ID)
);

ALTER TABLE GO_SHOWROOM_VISIT
    ADD IS_DELETED BIT NOT NULL DEFAULT 0;

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO) VALUES
                                                                    ('CUCINE', NULL, 1),
                                                                    ('INFISSI', NULL, 1),
                                                                    ('PORTE', NULL, 1),
                                                                    ('SOLUZIONI BAGNO', NULL, 1),
                                                                    ('RISTRUTTURAZIONE', NULL, 1),
                                                                    ('ESTERNO', NULL, 1),
                                                                    ('IMPIANTISTICA', NULL, 1),
                                                                    ('RISCALDAMENTO', NULL, 1);

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'BOX DOCCIA', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'SOLUZIONI BAGNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'RUBINETTERIA', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'SOLUZIONI BAGNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'SANITARI', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'SOLUZIONI BAGNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'MOBILI DA BAGNO', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'SOLUZIONI BAGNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'RIVESTIMENTI E PAVIMENTI', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'SOLUZIONI BAGNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'PIAZZALE', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'ESTERNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'PISCINA', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'ESTERNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'FACCIATA', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'ESTERNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'GIARDINO', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'ESTERNO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'IMPIANTO A PAVIMENTO', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'IMPIANTISTICA';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'POMPE DI CALORE', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'IMPIANTISTICA';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'SCALDA BAGNO POMPA DI CALORE', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'IMPIANTISTICA';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'CONDIZIONAMENTO', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'IMPIANTISTICA';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'STUFE', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'RISCALDAMENTO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'CALDAIE', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'RISCALDAMENTO';

INSERT INTO GO_SHOWROOM_MOTIVO (DESCRIZIONE, PARENT_ID, ATTIVO)
SELECT 'CAMINETTI', ID, 1 FROM GO_SHOWROOM_MOTIVO WHERE DESCRIZIONE = 'RISCALDAMENTO';

CREATE TABLE GO_SEDE (
                      ID BIGINT IDENTITY(1,1) PRIMARY KEY,
                      CODICE VARCHAR(30) NOT NULL UNIQUE,
                      DESCRIZIONE VARCHAR(100) NOT NULL
);

INSERT INTO GO_SEDE (CODICE, DESCRIZIONE) VALUES
                                           ('CEGLIE', 'Showroom Ceglie'),
                                           ('OSTUNI', 'Showroom Ostuni');

ALTER TABLE GO_SHOWROOM_VISIT
    ADD SEDE_ID BIGINT NOT NULL DEFAULT 1;

ALTER TABLE GO_SHOWROOM_VISIT
    ADD CONSTRAINT FK_SHOWROOM_SEDE
        FOREIGN KEY (SEDE_ID) REFERENCES GO_SEDE(ID);