CREATE TABLE GO_APPUNTAMENTO
(
    ID BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,

    SEDE_ID BIGINT NOT NULL,

    GRUPPO_CONTO INT NULL,
    SOTTO_CONTO VARCHAR(6) NULL,

    NOME_CLIENTE VARCHAR(150) NOT NULL,
    TELEFONO VARCHAR(50) NULL,
    EMAIL VARCHAR(255) NULL,

    VIA VARCHAR(255) NULL,
    CIVICO VARCHAR(20) NULL,
    CAP VARCHAR(10) NULL,
    COMUNE VARCHAR(100) NULL,
    PROVINCIA VARCHAR(2) NULL,

    DATA_APPUNTAMENTO DATE NOT NULL,

    ORA_DA TIME NOT NULL,
    ORA_A TIME NOT NULL,

    COD_VENDITORE VARCHAR(3) NOT NULL,

    ID_MOTIVO BIGINT NOT NULL,

    NOTE VARCHAR(2000) NULL,

    PROMEMORIA_INVIATO BIT NOT NULL DEFAULT 0,

    CREATED_AT DATETIME2 NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME2 NULL,

    CREATED_BY VARCHAR(100) NULL,
    UPDATED_BY VARCHAR(100) NULL,

    CONSTRAINT FK_GO_APPUNTAMENTO_SEDE
        FOREIGN KEY (SEDE_ID)
            REFERENCES GO_SEDE(ID),

    CONSTRAINT FK_GO_APPUNTAMENTO_MOTIVO
        FOREIGN KEY (ID_MOTIVO)
            REFERENCES GO_SHOWROOM_MOTIVO(ID)
);
GO

CREATE INDEX IX_GO_APPUNTAMENTO_DATA
    ON GO_APPUNTAMENTO(DATA_APPUNTAMENTO);

CREATE INDEX IX_GO_APPUNTAMENTO_VENDITORE
    ON GO_APPUNTAMENTO(COD_VENDITORE);

CREATE INDEX IX_GO_APPUNTAMENTO_SEDE
    ON GO_APPUNTAMENTO(SEDE_ID);

CREATE INDEX IX_GO_APPUNTAMENTO_MOTIVO
    ON GO_APPUNTAMENTO(ID_MOTIVO);
GO

ALTER TABLE GO_APPUNTAMENTO
    ADD OUTLOOK_EVENT_ID VARCHAR(255) NULL;